import createConstants from '../utils';

export default createConstants(
    'LOAD_EMBEDDED_DATA_REQUEST',
    'LOAD_EMBEDDED_DATA_SUCCESS',
    'FETCH_PROCEDURES_REQUEST',
    'FETCH_PROCEDURES_ERROR',
    'FETCH_PROCEDURES_SUCCESS',
    'FETCH_FOLDERS_REQUEST',
    'FETCH_FOLDERS_ERROR',
    'FETCH_FOLDERS_SUCCESS',
    'ROUTE_TO_LOCATION_REQUEST',
    'ROUTE_TO_LOCATION_SUCCESS'
);
